.gitignore
SXR/Extensions/platformsdk_support/build.gradle
SXR/Extensions/sxr-particlesystem/build.gradle
SXR/Extensions/sxr-physics/build.gradle
SXR/SDK/backend_daydream/build.gradle
SXR/SDK/backend_monoscopic/build.gradle
SXR/SDK/backend_oculus/build.gradle
SXR/SDK/sxrsdk/build.gradle

By default all supported abis are built. This slows down the build considerably so one can explicitly request only one abi by setting SXRSDK_ABI_FILTER.
``SXRSDK_ABI_FILTER="armeabi-v7a"``

Support x86, x86_64 abis

---

SXR/Extensions/script/src/main/java/com/samsungxr/script/SXRScriptManager.java

changing the context variable from "gvrf" to "sxr"

changing the context variable

---

SXR/Extensions/MixedReality/src/main/java/com/samsungxr/mixedreality/CVLibrary/CVLibraryAnchor.java
SXR/Extensions/MixedReality/src/main/java/com/samsungxr/mixedreality/CVLibrary/CVLibraryAugmentedImage.java
SXR/Extensions/MixedReality/src/main/java/com/samsungxr/mixedreality/CVLibrary/CVLibraryHelper.java
SXR/Extensions/MixedReality/src/main/java/com/samsungxr/mixedreality/CVLibrary/CVLibraryLightEstimate.java
SXR/Extensions/MixedReality/src/main/java/com/samsungxr/mixedreality/CVLibrary/CVLibraryPlane.java
SXR/Extensions/MixedReality/src/main/java/com/samsungxr/mixedreality/CVLibrary/CVLibraryPose.java
SXR/Extensions/MixedReality/src/main/java/com/samsungxr/mixedreality/CVLibrary/CVLibrarySession.java
SXR/Extensions/MixedReality/src/main/java/com/samsungxr/mixedreality/SXRMixedReality.java

Added CV library session for used in Mixed Reality extensions instead of ARCore dependence. The CV Library session will work in a headset with external camera and place a plane on the marker with an object on the center of that plane.

Cv lib integration

---

SXR/Extensions/MixedReality/src/main/java/com/samsungxr/mixedreality/SXRMixedReality.java

add some default contstructors so sxr-arcore doesn't break.
also added some javadoc.  but lots of javadoc is still missing. :(

add some default contstructors so sxr-arcore doesn't break

---

SXR/SDK/sxrsdk/src/main/java/com/samsungxr/SXRJassimpAdapter.java
SXR/SDK/sxrsdk/src/main/java/com/samsungxr/shaders/SXRTextureShader.java
SXR/SDK/sxrsdk/src/main/java/com/samsungxr/shaders/SXRVertexColorShader.java
SXR/SDK/sxrsdk/src/main/res/raw/vcolor_surface.fsh
SXR/SDK/sxrsdk/src/main/res/raw/vcolor_vertex.vsh
SXR/SDK/sxrsdk/src/main/res/raw/vertex_template.vsh

If vertex colors are found in a mesh, Jassimp will now use GVRVertexColorShader instead of GVRPhongShader. The vertex color shader has been rewritten to allow lighting if normals are also present in the mesh.
GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com
This PR has not been tested yet. It is for Mitch to review.
Original PR: https://github.com/Samsung/GearVRf/pull/2006
SXR-DCO-1.0-Signed-off-by: Mihail Marinov m.marinov@samsung.com

Support vertex color shader in jassimp

---

SXR/Extensions/MixedReality/src/main/java/com/samsungxr/mixedreality/SXRMixedReality.java

auto detect the drop-in device for the mixed reality extension

auto detect the drop-in device for the mixed reality extension

---

SXR/SDK/sxrsdk/src/main/java/com/samsungxr/nodes/SXRTextViewNode.java

I found a bug when creating a new `SXRTextViewNode` with width value that equals height value (e.g: `20.0f`). The current behaviour make the text incredibly small because the `canvasWidth` and `canvasHeight` is left unmodified and in turn made the `LayoutParams` initialized with too large parameters. 
This is because the following condition didn't account for the case where `canvasWidth == canvasHeight`.
This PR add the above edge case to process too.
SXR DCO signed off by: Luong Vu luongvm183@gmail.com

Fix SXRTextViewNode text small bug when width equals height

---

SXR/SDK/backend_monoscopic/src/main/java/com/samsungxr/MonoscopicViewManager.java
SXR/SDK/sxrsdk/src/main/jni/gl/gl_render_texture.cpp
SXR/SDK/sxrsdk/src/main/jni/gl/gl_render_texture.h

fix suspicious things about rendertargets in monoscopic.  mainly that
the creation routine for non-multisample rendertargets was significantly
different that multisampled ones.
this doesn't fix sxr-shadows, simplephysics, rendertotexture, or
blurfilter.  but they are all related to rendertargets in monoscopic.

fix suspicious things about rendertargets in monoscopic

---

SXR/SDK/backend_monoscopic/src/main/java/com/samsungxr/MonoscopicViewManager.java
SXR/SDK/sxrsdk/src/main/java/com/samsungxr/SXRRenderTarget.java
SXR/SDK/sxrsdk/src/main/jni/engine/renderer/gl_renderer.cpp
SXR/SDK/sxrsdk/src/main/jni/engine/renderer/gl_renderer.h
SXR/SDK/sxrsdk/src/main/jni/engine/renderer/renderer.h
SXR/SDK/sxrsdk/src/main/jni/engine/renderer/vulkan_renderer.cpp
SXR/SDK/sxrsdk/src/main/jni/engine/renderer/vulkan_renderer.h
SXR/SDK/sxrsdk/src/main/jni/gl/gl_render_target.h
SXR/SDK/sxrsdk/src/main/jni/objects/components/render_target.cpp
SXR/SDK/sxrsdk/src/main/jni/objects/components/render_target.h
SXR/SDK/sxrsdk/src/main/jni/objects/components/render_target_jni.cpp
SXR/SDK/sxrsdk/src/main/jni/vulkan/vk_render_target.cpp
SXR/SDK/sxrsdk/src/main/jni/vulkan/vk_render_target.h

Fixes render target issues with monoscopic backend. There are two issues that have been fixed in this PR.
We are using default fbo for monoscopic backend, so our rendertargets do not have rendertextures in them. After drawing to a separate render target in case of demos such as rendertotexture, we were not unbinding the fbo and therefore, nothing was being rendered on the default fbo. The second issue was that the viewport was not being set correctly in demos such as shadows and simplephysics.

fix fbo and viewport issues with monoscopic backend

---

SXR/Extensions/widgetLib/src/com/samsungxr/widgetlib/main/WidgetLib.java
SXR/Extensions/widgetLib/src/com/samsungxr/widgetlib/widget/TouchManager.java

Instead of cleaning up the controllers in response to onDestroy(),
clean them up in response to onPause().  If onDestroy() doesn't get
called for some reason, skipping the clean up seems to cause
intermittent issues for subsequent apps; onPause() is, in some
circumstances, a more reliable place to do this.

Cleans up controllers in onPause()

---

SXR/SDK/sxrsdk/src/main/java/com/samsungxr/SXRMesh.java
SXR/SDK/sxrsdk/src/main/java/com/samsungxr/SXRTexture.java
SXR/SDK/sxrsdk/src/main/jni/gl/gl_bitmap_image.cpp
SXR/SDK/sxrsdk/src/main/jni/gl/gl_cubemap_image.cpp
SXR/SDK/sxrsdk/src/main/jni/objects/components/render_data.cpp
SXR/SDK/sxrsdk/src/main/jni/objects/components/render_data.h
SXR/SDK/sxrsdk/src/main/jni/objects/index_buffer.cpp
SXR/SDK/sxrsdk/src/main/jni/objects/index_buffer.h
SXR/SDK/sxrsdk/src/main/jni/objects/index_buffer_jni.cpp
SXR/SDK/sxrsdk/src/main/jni/objects/textures/bitmap_image.cpp
SXR/SDK/sxrsdk/src/main/jni/objects/textures/bitmap_image.h
SXR/SDK/sxrsdk/src/main/jni/objects/textures/cubemap_image.h
SXR/SDK/sxrsdk/src/main/jni/objects/textures/float_image.cpp
SXR/SDK/sxrsdk/src/main/jni/objects/textures/float_image.h
SXR/SDK/sxrsdk/src/main/jni/objects/textures/image.h
SXR/SDK/sxrsdk/src/main/jni/objects/textures/texture.cpp
SXR/SDK/sxrsdk/src/main/jni/objects/textures/texture.h
SXR/SDK/sxrsdk/src/main/jni/objects/textures/texture_jni.cpp
SXR/SDK/sxrsdk/src/main/jni/objects/vertex_buffer.cpp
SXR/SDK/sxrsdk/src/main/jni/objects/vertex_buffer.h
SXR/SDK/sxrsdk/src/main/jni/objects/vertex_buffer_jni.cpp
SXR/SDK/sxrsdk/src/main/jni/util/jni_utils.h

1. Throw out of memory exceptions from vertex and index buffers
2. Check for exceptions in bindShaderNative
3. Add SXRImage.clearData() to allow test to clear C++ references to image (like the rendering loop does)
4. Removed weak reference to unused java image

Improve out of memory behavior

---

SXR/Extensions/MixedReality/src/main/java/com/samsungxr/mixedreality/SXRMixedReality.java
SXR/Extensions/ResonanceAudio/resonanceaudio/src/main/java/com/samsungxr/resonanceaudio/SXRAudioManager.java
SXR/SDK/sxrsdk/src/main/java/com/samsungxr/IApplicationEvents.java
SXR/SDK/sxrsdk/src/main/java/com/samsungxr/SXRApplication.java
SXR/SDK/sxrsdk/src/main/java/com/samsungxr/SXREventListeners.java
SXR/SDK/sxrsdk/src/main/java/com/samsungxr/io/SXRAndroidWearTouchpad.java
SXR/SDK/sxrsdk/src/main/java/com/samsungxr/io/SXRGearCursorController.java
SXR/SDK/sxrsdk/src/main/java/com/samsungxr/nodes/SXRCameraNode.java
SXR/SDK/sxrsdk/src/main/java/com/samsungxr/nodes/SXRVideoNode.java

Renamed IActivityEvents to the more appropriate IApplicationEvents (since the app is the target for these)

Fix for the TestSendEvents test - controller class sending events now to the right target (app)

---

SXR/SDK/sxrsdk/src/main/java/com/samsungxr/nodes/SXRKeyboardNode.java

* Fix hover and keypress on mini keyboard(popup keyboard).
* Fix UI thread exception.
Known issue: delete key is not working anymore. It may be related to some upgrade
of Android OS. 
SXR-DCO-1.0-Signed-off-by: Ragner Magalhaes <ragner.n@samsung.com>

Mini keyboard working again

---

SXR/SDK/sxrsdk/src/main/java/com/samsungxr/io/SXRGazeCursorController.java

* I am using the cam's aspect ratio to calc the dimension
of the plane at "display depth" and converting the
display's touch position to a position in the plane.
SXR-DCO-1.0-Signed-off-by: Ragner Magalhaes <ragner.n@samsung.com>

Calc touch position on plane at display depth

---

SXR/SDK/backend_oculus/src/main/java/com/samsungxr/OvrControllerReader.java
SXR/SDK/backend_oculus/src/main/java/com/samsungxr/OvrViewManager.java
SXR/SDK/sxrsdk/src/main/java/com/samsungxr/io/SXRGearCursorController.java
SXR/SDK/sxrsdk/src/main/jni/objects/textures/image.h
SXR/SDK/sxrsdk/src/main/jni/objects/textures/texture.cpp

Fix back key handling in Oculus GO
Texture dtor crash reproducible often enough on Oculus GO with sxr-controller.
Back key special cased since when there is a controller events emulation is turned off (no automatic back key propagation to the activity).
Issue: https://github.com/sxrsdk/sxrsdk/issues/82

Fix crash in Texture dtor

---

SXR/SDK/sxrsdk/src/main/java/com/samsungxr/animation/SXRBodyTracker.java
SXR/SDK/sxrsdk/src/main/java/com/samsungxr/nodes/SXRCameraNode.java

Added public setter and getter functions to SXRCameraNode for the android camera parameters.
Added a public api for adding the preview callback.
Removed camera object from SXRBodyTracker, ownership of camera is now with the SXRCameraNode.
SXR DCO signed off by: Sushant Ojal sushant.o@samsung.com

Fix activity lifecycle management of camera for SXRBodyTracker

---

SXR/SDK/backend_oculus/src/main/java/com/samsungxr/OvrViewManager.java
SXR/SDK/backend_oculus/src/main/jni/ovr_activity.cpp
SXR/SDK/backend_oculus/src/main/jni/ovr_activity.h
SXR/SDK/backend_oculus/src/main/jni/ovr_activity_jni.cpp

Added only for Oculus, not part of the public API
To call, assuming the app is using the Oculus backend, do this:
```
try {
Method m = mGvrContext.getClass().getMethod("recenterPose");
m.invoke(mGvrContext);
} catch (final Exception e) {
e.printStackTrace();
}
```

Add Oculus-specific recenterPose

---

SXR/Extensions/MixedReality/src/main/java/com/samsungxr/mixedreality/CVLibrary/CVLibraryPlane.java
SXR/Extensions/MixedReality/src/main/java/com/samsungxr/mixedreality/SXRPlane.java
SXR/Extensions/MixedReality/src/main/java/com/samsungxr/mixedreality/arcore/ARCorePlane.java

This is needed to detect the plane normals.
Signed-off-by: Andrei Huziuk <andrei@inizio.io>
Signed-off-by: Moiz Sonasath <m.sonasath@samsung.com>

Expose ARCore's "public Pose getCenterPose ()" api for SXR apps

---

SXR/Extensions/widgetLib/src/com/samsungxr/widgetlib/widget/RenderDataCache.java
SXR/Extensions/widgetLib/src/com/samsungxr/widgetlib/widget/Widget.java
SXR/Extensions/widgetLib/src/com/samsungxr/widgetlib/widget/basic/TextWidget.java
SXR/SDK/sxrsdk/src/main/java/com/samsungxr/animation/SXRAvatar.java

Most of the other SXRRenderData functions are there, this one is missing.

Add alpha blend support to widgets, make them not cast shadows

---

SXR/SDK/backend_daydream/src/main/jni/daydream_renderer.cpp

Fixes sxr-shadows and any app that directly sets the position of the camera rig.

daydream: apply position to the head transform

---

SXR/SDK/sxrsdk/src/main/java/com/samsungxr/SXRShaderTemplate.java

One of the #defines for the shader was set wrong causing a necessary line to be omitted

Fix bug with 2 sets of texture coordinates

---

SXR/Extensions/MixedReality/src/main/java/com/samsungxr/mixedreality/arcore/ARCoreAnchor.java
SXR/SDK/sxrsdk/src/main/java/com/samsungxr/animation/SXRAnimationQueue.java
SXR/SDK/sxrsdk/src/main/java/com/samsungxr/animation/SXRAvatar.java

SXRAvatar.startAll now takes a name and will start only matching animations
SXRAvatar.startNext will start an animation as the next one to run
Also removed debug printout from mixedreality

New animation apis

---

SXR/SDK/sxrsdk/src/main/java/com/samsungxr/SXRRenderData.java
SXR/SDK/sxrsdk/src/main/jni/gl/gl_render_texture.cpp
SXR/SDK/sxrsdk/src/main/jni/gl/gl_render_texture.h
SXR/SDK/sxrsdk/src/main/jni/objects/components/render_data.h
SXR/SDK/sxrsdk/src/main/jni/objects/components/render_data_jni.cpp

.. including an unused pbo in every render texture.

Remove the last remnants of the TextureCapturer..

---

SXR/SDK/backend_oculus/src/main/java/com/samsungxr/OvrActivityDelegate.java

remove explicitly setting the default framebuffer width and height and
allow it to be queried from the Oculus SDK.
the code in ovr_configuration_helper.cpp checks to see if the width or
height are -1 (which is what they are initialized to) and if so, uses
the value provided by the Oculus SDK.  By setting the width and height
in OvrActivityDelegate.java, that check is bypassed.
this appears to be one reason why apps on Quest look so funky right now.
Eyebuffer on Quest are rectangular, not square.  The other appears to be related to needing 
an asymmetric view frustum.  I'm still working on that issue.
SXR-DCO-1.0-Signed-off-by: Tom Flynn

fix for Quest

---

SXR/SDK/backend_oculus/src/main/jni/ovr_activity.cpp
SXR/SDK/backend_oculus/src/main/jni/ovr_activity.h
SXR/SDK/sxrsdk/src/main/jni/objects/components/camera.h
SXR/SDK/sxrsdk/src/main/jni/objects/components/custom_camera.h
SXR/SDK/sxrsdk/src/main/jni/objects/components/orthogonal_camera.cpp
SXR/SDK/sxrsdk/src/main/jni/objects/components/orthogonal_camera.h
SXR/SDK/sxrsdk/src/main/jni/objects/components/perspective_camera.cpp
SXR/SDK/sxrsdk/src/main/jni/objects/components/perspective_camera.h

add asymmetric projection support for Quest.
I think this fixes most (all?) of the visual issues with Quest at this point.  Still needs to be tested against GearVR.  Next I'll need to verify the controllers.
SXR-DCO-1.0-Signed-off-by: Tom Flynn

asymmetric projection support for Quest

---

SXR/Extensions/MixedReality/src/main/java/com/samsungxr/mixedreality/CVLibrary/CVLibrarySession.java

there were two resume() methods.  probably due to a merge mishap.

build fix for MixedReality extension
