SXR/Extensions/3DCursor/IODevices/gearwear/PhoneSide/gearwearlibrary/build.gradle, SXR/Extensions/WearTouchPad/mobile/build.gradle, SXR/Extensions/WearTouchPad/wear/build.gradle, SXR/Extensions/sxr-physics/src/main/jni/CMakeLists.txt, SXR/SDK/backend_monoscopic/build.gradle, SXR/SDK/backend_oculus/build.gradle
more spots that needed converting to sxr
=> more spots that needed converting to sxr

SXR/SDK/backend_monoscopic/build.gradle, SXR/SDK/build.gradle, SXR/SDK/gradle.properties, SXR/SDK/gradle/wrapper/gradle-wrapper.properties, SXR/SDK/sxrsdk/src/main/AndroidManifest.xml, SXR/SDK/sxrsdk/src/main/res/values/styles.xml
=> Stop build warnings about android.enableAapt2=false

SXR/Extensions/3DCursor/3DCursorLibrary/build.gradle, SXR/Extensions/3DCursor/IODevices/gearwear/GearWearIoDevice/build.gradle, SXR/Extensions/3DCursor/IODevices/gearwear/PhoneSide/gearwearlibrary/build.gradle, SXR/Extensions/DebugWebServer/debugwebserver/build.gradle, SXR/Extensions/MixedReality/build.gradle, SXR/Extensions/ResonanceAudio/resonanceaudio/build.gradle, SXR/Extensions/SceneSerializer/sceneserializer/build.gradle, SXR/Extensions/WidgetPlugin/widgetplugin/build.gradle, SXR/Extensions/build.gradle, SXR/Extensions/gradle.properties, SXR/Extensions/gradle/wrapper/gradle-wrapper.properties, SXR/Extensions/script/build.gradle, SXR/Extensions/sxr-particlesystem/build.gradle, SXR/Extensions/sxr-physics/build.gradle, SXR/Extensions/widgetLib/build.gradle, SXR/Extensions/x3d/build.gradle, SXR/SDK/backend_daydream/build.gradle, SXR/SDK/backend_monoscopic/build.gradle, SXR/SDK/backend_oculus/build.gradle, SXR/SDK/sxrsdk/build.gradle
=> gradle: fix publishing of aars, bring extensions up to date

SXR/Extensions/3DCursor/3DCursorLibrary/build.gradle, SXR/Extensions/3DCursor/IODevices/gearwear/GearWearIoDevice/build.gradle, SXR/Extensions/3DCursor/IODevices/gearwear/PhoneSide/gearwearlibrary/build.gradle, SXR/Extensions/DebugWebServer/debugwebserver/build.gradle, SXR/Extensions/ResonanceAudio/resonanceaudio/build.gradle, SXR/Extensions/SceneSerializer/sceneserializer/build.gradle, SXR/Extensions/script/build.gradle, SXR/Extensions/sxr-particlesystem/build.gradle, SXR/Extensions/sxr-physics/build.gradle, SXR/Extensions/widgetLib/build.gradle, SXR/Extensions/x3d/build.gradle
=> extensions, gradle: fix deprecation warnings

SXR/SDK/sxrsdk/src/main/java/com/samsungxr/SXRVersion.java
=> up the version number to 5

SXR/Extensions/script/src/main/java/com/samsungxr/script/SXRScriptManager.java, SXR/SDK/sxrsdk/src/main/java/com/samsungxr/SXRJassimpAdapter.java, SXR/SDK/sxrsdk/src/main/java/com/samsungxr/shaders/SXRPhongLayeredShader.java, SXR/SDK/sxrsdk/src/main/java/com/samsungxr/shaders/SXRPhongShader.java, SXR/SDK/sxrsdk/src/main/java/com/samsungxr/shaders/SXRTextureShader.java, SXR/SDK/sxrsdk/src/main/java/com/samsungxr/shaders/SXRVertexColorShader.java, SXR/SDK/sxrsdk/src/main/res/raw/fragment_template.fsh, SXR/SDK/sxrsdk/src/main/res/raw/fragment_template_multitex.fsh, SXR/SDK/sxrsdk/src/main/res/raw/phong_surface.fsh, SXR/SDK/sxrsdk/src/main/res/raw/phong_surface_layertex.fsh, SXR/SDK/sxrsdk/src/main/res/raw/phong_surface_multitex.fsh, SXR/SDK/sxrsdk/src/main/res/raw/texture_surface.fsh, SXR/SDK/sxrsdk/src/main/res/raw/vcolor_surface.fsh, SXR/SDK/sxrsdk/src/main/res/raw/vcolor_vertex.vsh, SXR/SDK/sxrsdk/src/main/res/raw/vertex_template.vsh, SXR/SDK/sxrsdk/src/main/res/raw/vertex_template_multitex.vsh
This PR merges work from PR #2006 (GearVRf) and PR #2008 (GearVRf). It adds support for vertex color into the Phong and Texture shaders.
=> Vertex color support

SXR/SDK/backend_monoscopic/src/main/java/com/samsungxr/MonoscopicViewManager.java, SXR/SDK/sxrsdk/src/main/java/com/samsungxr/SXRContext.java, SXR/SDK/sxrsdk/src/main/java/com/samsungxr/SXRRenderTarget.java, SXR/SDK/sxrsdk/src/main/jni/engine/renderer/gl_renderer.cpp, SXR/SDK/sxrsdk/src/main/jni/engine/renderer/gl_renderer.h, SXR/SDK/sxrsdk/src/main/jni/engine/renderer/renderer.h, SXR/SDK/sxrsdk/src/main/jni/engine/renderer/vulkan_renderer.cpp, SXR/SDK/sxrsdk/src/main/jni/engine/renderer/vulkan_renderer.h, SXR/SDK/sxrsdk/src/main/jni/gl/gl_render_target.h, SXR/SDK/sxrsdk/src/main/jni/gl/gl_render_texture.cpp, SXR/SDK/sxrsdk/src/main/jni/gl/gl_render_texture.h, SXR/SDK/sxrsdk/src/main/jni/objects/components/render_target.cpp, SXR/SDK/sxrsdk/src/main/jni/objects/components/render_target.h, SXR/SDK/sxrsdk/src/main/jni/objects/components/render_target_jni.cpp, SXR/SDK/sxrsdk/src/main/jni/vulkan/vk_render_target.cpp, SXR/SDK/sxrsdk/src/main/jni/vulkan/vk_render_target.h
On top of https://github.com/sxrsdk/sxrsdk/pull/40
=>  Fixes for sxr-blurfilter

SXR/Extensions/MixedReality/src/main/java/com/samsungxr/mixedreality/CVLibrary/CVLibrarySession.java
…eality/CVLibrary/CVLibrarySession.java
remove code that ffreezes camera
=> [release_v5.0] Fix tracking issue in cvlib

SXR/Extensions/MixedReality/src/main/java/com/samsungxr/mixedreality/CVLibrary/CVLibrarySession.java
…eality/CVLibrary/CVLibrarySession.java
rremove code that ffreezes camera
=> Fix tracking issue in cvlib

.travis.yml
first crack at travis integration
=> first crack at travis integration

SXR/SDK/maven.properties
=> Set up for 5.0.1 snapshots upload

.travis.yml
=> Travis update ndk to r18b

SXR/Extensions/3DCursor/IODevices/gearwear/GearWearIoDevice/build.gradle, SXR/Extensions/widgetLib/build.gradle, SXR/SDK/maven.properties
=> [release_v5.0] Updates necessary to make the maven release

SXR/SDK/sxrsdk/src/main/java/com/samsungxr/SXRJassimpAdapter.java, SXR/SDK/sxrsdk/src/main/java/com/samsungxr/io/SXRInputManager.java, SXR/SDK/sxrsdk/src/main/res/raw/phong_surface_layertex.fsh
This patch fixes the skinned animation in the Rowboat model in sxr-javascript
=> Skinned animation bug fix

SXR/SDK/backend_daydream/src/main/AndroidManifest.xml, SXR/SDK/backend_monoscopic/src/main/AndroidManifest.xml, SXR/SDK/backend_oculus/src/main/AndroidManifest.xml
=> oculus: have manifest merging add the vr_only tag

SXR/SDK/sxrsdk/src/main/java/com/samsungxr/nodes/SXRTextViewNode.java, SXR/SDK/sxrsdk/src/main/res/raw/vertex_template_depth.vsh
=> Fix shadow mapping regression for skinned characters

SXR/SDK/backend_monoscopic/src/main/java/com/samsungxr/MonoscopicViewManager.java
=> Add left&right screenshot support to the monoscopic backend

SXR/Extensions/widgetLib/src/com/samsungxr/widgetlib/widget/WidgetPickHandler.java, SXR/SDK/sxrsdk/src/main/java/com/samsungxr/io/SXRCursorController.java
Adapted from https://github.com/Samsung/GearVRf/pull/2007
SXR-DCO-1.0-Signed-off-by: Svetlana Gurenkova s.gurenkova@samsung.com
=> clone Motion Event to use it in GVRPicker

SXR/SDK/sxrsdk/src/main/jni/engine/renderer/gl_renderer.cpp, SXR/SDK/sxrsdk/src/main/jni/gl/gl_render_texture.cpp
=> Fix invalidate for monoscopic; avoids tons of misleading warnings in logcat

SXR/SDK/sxrsdk/src/main/jni/objects/components/render_data.cpp
+ improve the exception handling
=> Fix compiler warning

SXR/SDK/sxrsdk/src/main/java/com/samsungxr/animation/SXRPoseMapper.java
This accessor allows applications to get the bone mapping between source and target skeletons from the pose mapper
=> Added SXRPoseMapper.getBoneMap

SXR/Extensions/3DCursor/IODevices/gearwear/GearWearIoDevice/build.gradle, SXR/Extensions/x3d/build.gradle
+ cleanup
Issue: https://github.com/google/ExoPlayer/issues/5225
=> ExoPlayer related build fix

SXR/SDK/backend_oculus/src/main/java/com/samsungxr/OvrControllerReader.java
=> Oculus GO: avoid double back key events

.travis.yml
doing this to make sure we don't commit changes that break the demos.
will do the same for the tests soon.
=> build the demos after building the framework.

SXR/SDK/sxrsdk/src/main/java/com/samsungxr/SXRJassimpAdapter.java, SXR/SDK/sxrsdk/src/main/java/com/samsungxr/animation/SXRAvatar.java, SXR/SDK/sxrsdk/src/main/java/com/samsungxr/animation/SXRPose.java, SXR/SDK/sxrsdk/src/main/java/com/samsungxr/animation/SXRSkeleton.java, SXR/SDK/sxrsdk/src/main/java/com/samsungxr/animation/SXRSkin.java, SXR/SDK/sxrsdk/src/main/java/com/samsungxr/animation/keyframe/BVHImporter.java, SXR/SDK/sxrsdk/src/main/java/com/samsungxr/animation/keyframe/SXRSkeletonAnimation.java, SXR/SDK/sxrsdk/src/main/jni/objects/components/skeleton.cpp, SXR/SDK/sxrsdk/src/main/jni/objects/components/skeleton.h, SXR/SDK/sxrsdk/src/main/jni/objects/components/skeleton_jni.cpp, SXR/SDK/sxrsdk/src/main/jni/objects/components/skin.cpp, SXR/SDK/sxrsdk/src/main/jni/objects/components/skin.h, SXR/SDK/sxrsdk/src/main/jni/objects/components/skin_jni.cpp
1. Fix bugs wth SXRSkeleton.merge
2. Update native skeleton and skin with new bone indices
3. Lock around skin bone map access
=> Fix bugs with skeleton merging

SXR/SDK/sxrsdk/src/main/java/com/samsungxr/animation/SXRBodyTracker.java
=> Define missing interface function in SXRBodyTracker.TrackerEvents

SXR/Extensions/sxr-physics/src/main/java/com/samsungxr/physics/SXRRigidBody.java, SXR/Extensions/sxr-physics/src/main/java/com/samsungxr/physics/SXRWorld.java, SXR/Extensions/sxr-physics/src/main/jni/engine/bullet/bullet_rigidbody.cpp, SXR/Extensions/sxr-physics/src/main/jni/engine/bullet/bullet_rigidbody.h, SXR/Extensions/sxr-physics/src/main/jni/engine/bullet/bullet_world.cpp, SXR/Extensions/sxr-physics/src/main/jni/engine/physics_rigidbody.h, SXR/Extensions/sxr-physics/src/main/jni/engine/physics_rigidbody_jni.cpp
Changes to support the new AR demo (see https://github.com/sxrsdk/sxrsdk-demos/pull/60)
=> Fixes and updates to support AR Pet demo

SXR/SDK/sxrsdk/src/main/java/com/samsungxr/animation/SXRPose.java, SXR/SDK/sxrsdk/src/main/java/com/samsungxr/animation/SXRPoseMapper.java, SXR/SDK/sxrsdk/src/main/java/com/samsungxr/animation/SXRSkeleton.java, SXR/SDK/sxrsdk/src/main/java/com/samsungxr/animation/keyframe/SXRSkeletonAnimation.java, SXR/SDK/sxrsdk/src/main/jni/objects/components/skeleton.cpp
Fixes problems with adding new bones to an existing skeleton
=> bug fixes in SXRPose.inverse, SXRSkeleton.merge

SXR/SDK/sxrsdk/src/main/jni/objects/components/mesh_collider.cpp
Copied from https://github.com/Samsung/GearVRf/pull/2033
=> MeshCollider: return distance in world coordinate

SXR/SDK/backend_oculus/src/main/java/com/samsungxr/OvrVrapiActivityHandler.java
=> oculus_adapter: fix for android p

SXR/Extensions/MixedReality/src/main/java/com/samsungxr/mixedreality/arcore/ARCoreSession.java
=> mixed reality ext: build fix

SXR/Extensions/MixedReality/src/main/java/com/samsungxr/mixedreality/CVLibrary/CVLibrarySession.java, SXR/Extensions/MixedReality/src/main/java/com/samsungxr/mixedreality/IMixedReality.java, SXR/Extensions/MixedReality/src/main/java/com/samsungxr/mixedreality/SXRMixedReality.java, SXR/Extensions/MixedReality/src/main/java/com/samsungxr/mixedreality/arcore/ARCoreSession.java
SXR-DCO-1.0-Signed-off-by: Moiz Sonasath <m.sonasath@samsung.com>
=> Expose ARcore's acquireCameraImage() API.

SXR/Extensions/platformsdk_support/src/main/java/com/samsungxr/PlatformEntitlementCheck.java, SXR/SDK/backend_oculus/src/main/jni/ovr_activity.cpp
needed to feed the position info to the camera rig.
found a missed gvrf -> sxr conversion
SXR-DCO-1.0-Signed-off-by: Tom Flynn 
=> initial tweaks for Oculus Quest

SXR/SDK/sxrsdk/src/main/java/com/samsungxr/SXRMaterial.java, SXR/SDK/sxrsdk/src/main/java/com/samsungxr/nodes/SXRVideoNode.java, SXR/SDK/sxrsdk/src/main/java/com/samsungxr/shaders/SXROESHorizontal180StereoShader.java, SXR/SDK/sxrsdk/src/main/res/raw/oes_horizontal_180_stereo_frag.fsh, SXR/SDK/sxrsdk/src/main/res/raw/pos_tex_horiz_180_stereo_ubo.vsh
Hastily added VR180 shader needed for an internal demo.
SXR-DCO-Signed-off-by: Tom Flynn 
=> Add a VR180 shader

SXR/Extensions/widgetLib/build.gradle, SXR/Extensions/widgetLib/gradle.properties, SXR/Extensions/widgetLib/gradle/wrapper/gradle-wrapper.properties, SXR/SDK/backend_monoscopic/build.gradle, SXR/SDK/sxrsdk/build.gradle
Signed-off-by: Yufi Li <tai-yun.li@samsung.com>
=> update the versions to comply with other projects.

SXR/SDK/backend_daydream/build.gradle, SXR/SDK/backend_monoscopic/build.gradle, SXR/SDK/backend_oculus/build.gradle, SXR/SDK/build.gradle, SXR/SDK/gradle/wrapper/gradle-wrapper.properties, SXR/SDK/sxrsdk/build.gradle
=> Gradle upgrade

SXR/SDK/backend_daydream/build.gradle, SXR/SDK/backend_monoscopic/build.gradle, SXR/SDK/backend_oculus/build.gradle, SXR/SDK/sxrsdk/build.gradle
=> Gradle: copying aars around
